### ISSUE TITLE
Unknown property: DTS\eBaySDK\Trading\Types\ReviseInventoryStatusResponseType::ItemID

### ISSUE THREAD

**Issue by diego-vieira** [davidtsadler/ebay-sdk-trading#15]
Hello there, I'm trying to make a call to update the quantity and price, but I'm getting the following warning
```
Unknown property: DTS\eBaySDK\Trading\Types\ReviseInventoryStatusResponseType::ItemID 
```
```
$request = new Types\ReviseInventoryStatusRequestType();

$request->RequesterCredentials = new Types\CustomSecurityHeaderType();
$request->RequesterCredentials->eBayAuthToken = $token;

$item = new Types\InventoryStatusType();

$item->ItemID = "111111111111";
$item->StartPrice = new Types\AmountType(array('value' => 1.00));
$item->Quantity = 10;
$item->SKU = "1000";

$request->InventoryStatus[] = $item;
$response = $this->service->reviseInventoryStatus($request);
```
/vendor/dts/ebay-sdk/src/DTS/eBaySDK/Types/BaseType.php - 413

The strange thing is, the price and quantity is updated just fine.

**Comment by davidtsadler** [comment]
Do you have any code after the below line that is not shown in the example?

```
$response = $this->service->reviseInventoryStatus($request);
```

The error is coming from the `$response` object. For example the following would produce the same error

```
echo $response->ItemID;
```

**Comment by diego-vieira** [comment]
Hi @davidtsadler sorry for the late reply, yes you were right.
The issue was on the response.

**Comment by michabbb** [comment]
@diego-vieira i would suggest to use phpstorm with a nearly perfect autocomplete feature... because the SDK is so well php-documentated, with phpstorm you won´t do so many mistakes because you get a warning with every property that does not exist....

**Comment by diego-vieira** [comment]
@michabbb yeah I do use phpStorm, for some reason I thought there would be a ItemID in the response.
Thanks
