### ISSUE TITLE
How to specify item specifics?

### ISSUE THREAD

**Issue by martinbean** [davidtsadler/ebay-sdk-trading#16]
I am trying to add a fixed price item, but the eBay API gives me the following error:

> Listing is missing required item specific(s): "Size, Brand". Please provide the required item specifics.

In trying to digest the eBay API documentation, I came across [this page](http://developer.ebay.com/devzone/xml/docs/Reference/ebay/AddFixedPriceItem.html) that points to a `<ItemSpecifics>` node, but I can’t find a corresponding class in the `Types` namespace.

How, using this SDK, would I determine the `<ItemSpecifics>`? And is that even the correct place to define the Size and Brand attributes that the API is complaining are missing?

**Comment by michabbb** [comment]
have you seen this ? https://github.com/davidtsadler/ebay-sdk-trading/blob/7817670a13f528a2db648f59a81b8f44bfb6b663/src/DTS/eBaySDK/Trading/Types/ItemType.php#L72

**Comment by martinbean** [comment]
@michabbb I had not. Thank you!

**Comment by martinbean** [comment]
@michabbb Is there an example of how to define a name-value list? As I’m struggling to work out the syntax based on the doc blocks only. I’ve tried something like this to no avail:

```php
$item->ItemSpecifics = new NameValueListArrayType;
$item->ItemSpecifics->Brand = new NameValueListType;
$item->ItemSpecifics->Brand->Name = 'Brand';
$item->ItemSpecifics->Brand->Value = $product->brand;
```

**Comment by michabbb** [comment]
here´s a piece of my code, you need to use "NameValueList":

````php
$itemSpecifics = new NameValueListArrayType();
            foreach ($request->Attribute as $key => $value) {
                if ($value) {
                    $specific                       = new NameValueListType();
                    $specific->Name                 = str_replace('_', ' ', $key);
                    $specific->Value[]              = $value;
                    $itemSpecifics->NameValueList[] = $specific;
                }
            }
            $item->ItemSpecifics = $itemSpecifics;
````

**Comment by martinbean** [comment]
Thanks, @michabbb. Got it working with this:

```php
$brand = new NameValueListType;
$brand->Name = 'Brand';
$brand->Value[] = $product->brand;

$size = new NameValueListType;
$size->Name = 'Size';
$size->Value[] = 'L';

$item->ItemSpecifics = new NameValueListArrayType;
$item->ItemSpecifics->NameValueList[] = $brand;
$item->ItemSpecifics->NameValueList[] = $size;
```
