### ISSUE TITLE
Cannot return the correct order with GetSellingManagerSaleRecord

### ISSUE THREAD

**Issue by cornernote** [davidtsadler/ebay-sdk-trading#17]
Hello,

I'm sorry for the slightly off-topic question, this is not an issue with your SDK, but more of a problem with Ebay API, or my lack of understanding on how to use it to achieve what I want.

I have asked the question in detail here on stackoverflow:

http://stackoverflow.com/questions/29639696/cannot-return-the-correct-order-with-getsellingmanagersalerecord

If you are able to answer that would be awesome.  If not just close this issue as off-topic.

Thanks.

Best regards,
Brett

**Comment by davidtsadler** [comment]
I'm not overly familiar with the sales side of the API so I've tried to come up with an answer on [stackoverflow](http://stackoverflow.com/questions/29639696/cannot-return-the-correct-order-with-getsellingmanagersalerecord/29660154#29660154) just in case it's of use for anyone.
