### ISSUE TITLE
Curl Issue

### ISSUE THREAD

**Issue by stevukas** [davidtsadler/ebay-sdk-trading#19]
Hi, i got many times this error
PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 6: Couldn't resolve host 'api.ebay.com' [url] https://api.ebay.com/ws/api.dll' in Guzzle/Http/Curl/CurlMulti.php:359
How i could solve this issue ?
thanks

**Comment by michabbb** [comment]
you know what "Couldn't resolve host" means ?

**Comment by Uebix** [comment]
I have the same issue.
I know that is generally a DNS problem, but I try to use google dns and other dns on my server.
Is possible that it's some problem with guzzle? I think that is very difficult that ebay have problems with their domains resolution.

**Comment by michabbb** [comment]
i would try to debug the connect with a simple "echo" inside the code at the point, where the connection gets created, or you do a tcpdump and watch which hostname really gets used by guzzle....
