### ISSUE TITLE
cant set StoreCategoryID in ItemType to large int

### ISSUE THREAD

**Issue by cornernote** [davidtsadler/ebay-sdk-trading#20]
Setting to a large int (which is actually a float, same problem if i cast to string):
```
$item = new Types\ItemType();
$item->Storefront = new Types\StorefrontType;
$item->Storefront->StoreCategoryID = 7000000000;
```

gives error:
```
exception 'DTS\eBaySDK\Exceptions\InvalidPropertyTypeException' with message 'Invalid property type: DTS\eBaySDK\Trading\Types\StorefrontType::StoreCategoryID expected <integer>, got <double>'
```

casting to an int:
```
$item = new Types\ItemType();
$item->Storefront = new Types\StorefrontType;
$item->Storefront->StoreCategoryID = 7000000000;
var dump($item->Storefront->StoreCategoryID);
```

Gives an int that overflowed:
```
int(-1589934592)
```

How can I set StoreCategoryID to a large int?

**Comment by michabbb** [comment]
Maybe something similar happens to you like me in the past:

https://github.com/davidtsadler/ebay-sdk-trading/issues/6

**Comment by cornernote** [comment]
Thanks @michabbb ... any workaround that you know of (even if its hacky)?

My dev box is 32bit ubuntu, and i dont really want to rebuild it.  Live won't have an issue, its just when I am coding and testing.

**Comment by michabbb** [comment]
As 64bit is de facto Standard in these days, I really think the best you can do is, setup an up 2 date box, so you won't get any trouble. Maybe you find a hack for this framework, but what is with the next one you are using? The code of David's ebay projects is auto generated, so you will have a problem again if you use one of his other sdks. 
I really suggest to setup a up 2 date box so you won't have any problems at all.

**Comment by cornernote** [comment]
It's up to date, its just 32bit. =)

I had some issue when I tried to install 64bit ubuntu 14.04 in my windows dev box using vagrant.  Can't remember what it was.  Maybe I'll build it in docker this time to avoid the headache of rebuilding it next time.  

Thanks for the help.

**Comment by michabbb** [comment]
When working with Windows, I have my best experience with vmware, vagrant is a mess under Windows, but that's my personal opinion :-) and no, a 32 bit system may be up 2 date, but it's not state of the art.

**Comment by davidtsadler** [comment]
If you want a quick hack you can change Line 52 in [StorefrontType.php](https://github.com/davidtsadler/ebay-sdk-trading/blob/master/src/DTS/eBaySDK/Trading/Types/StorefrontType.php#L52) so that it's a string.

```
'type' => 'string',
```

It will mean that you will have to pass a string in your code. It also means that this code won't be compatible with your live machine unless the same changes to the SDK is done.

```
$item->Storefront->StoreCategoryID = '7000000000';
```
