### ISSUE TITLE
Invalid property type: DTS\eBaySDK\Trading\Types\AttributeType::Value

### ISSUE THREAD

**Issue by hpartidas** [davidtsadler/ebay-sdk-trading#21]
Hi David,

Recent started using your package to migrate my existing half connector to use the new API.

I keep running into the following and I'm not sure if it's my own ignorance or a bug so thought I'd post this here and let you decide.

The following code:

`$condition = new AttributeType();`
`$condition->attributeLabel = 'Condition';`
`$conditionValue = new ValType();`
`$conditionValue->ValueLiteral = $row['condition'];`
`$condition->Value = $conditionValue;`
`$attrTypes = new AttributeArrayType([$condition]);`

Produces the following:

`Invalid property type: DTS\eBaySDK\Trading\Types\AttributeType::Value expected <DTS\eBaySDK\Types\UnboundType>, got <DTS\eBaySDK\Trading\Types\ValType>`
`#0 /vendor/dts/ebay-sdk/src/DTS/eBaySDK/Types/BaseType.php(265): DTS\eBaySDK\Types\BaseType->setValue('DTS\\eBaySDK\\Tra...', 'Value', Object(DTS\eBaySDK\Trading\Types\ValType))`
`#1 /vendor/dts/ebay-sdk/src/DTS/eBaySDK/Types/BaseType.php(99): DTS\eBaySDK\Types\BaseType->set('DTS\\eBaySDK\\Tra...', 'Value', Object(DTS\eBaySDK\Trading\Types\ValType))`
`#2 /MyApp/eBayConnector.php(97): DTS\eBaySDK\Types\BaseType->__set('Value', Object(DTS\eBaySDK\Trading\Types\ValType))`
`#3 /MyApp/eBayConnector.php(60): MyApp\eBayConnector->doAction('Add')`
`#4 /index.php(19): MyApp\eBayConnector->doAddItems()`
`#5 {main}`

If I try changing the type to use an UnboundType like so:

`$condition = new AttributeType();`
`$condition->attributeLabel = 'Condition';`
`$condition->Value = new UnboundType('AttributeArray', 'Value', $row['condition']);`
`$attrTypes = new AttributeArrayType([$condition]);`

Then it tells me:

`Invalid property type: DTS\eBaySDK\Trading\Types\AttributeType::Value expected <DTS\eBaySDK\Types\ValType>, got <DTS\eBaySDK\Trading\Types\UnboundType>`

Like I said, not sure if this is a bug or just my ignorance, but would appreciate some light/input on the matter.

Thanks!

**Comment by michabbb** [comment]
You closed tg the issue without any comment, to help others it would be nice to tell where your mistake came from...

**Comment by hpartidas** [comment]
Good morning!

I apologize for not documenting after I spotted the error as it wasn't in the code but in my understanding of it.

After reading through the source and coming to terms with what bound properties are (Arrays), I resolved by assigning them to the property as arrays directly.

Previously the error was here:

`$conditionValue = new ValType();`
`$conditionValue->ValueLiteral = $row['condition'];`
`$condition->Value = $conditionValue;` <--- Bad assignment

Solution was to assign to an array or pass an array like so:

`$condition->Value[] = $conditionValue;`

or

`$condition->Value = [ $conditionValue ];` 
or
`$condition->Value = array( $conditionValue );` 

Unbound types are required to be arrays, the documentation (at least not that I could find) doesn't really say anything about and I had to do a little research to come to terms with it. So the problem was that I didn't understand what it was telling me when it was asking me for an Unbound type. 

Perhaps the error message could make some allusion like "Are you assigning an array" or something to be a bit more explicit.

Hope this helps someone else and thanks @michabbb for calling me out on the documentation bit!

**Comment by michabbb** [comment]
@hpartidas thanks. you always have to look to the properties in the [code](https://github.com/davidtsadler/ebay-sdk-trading/blob/56e9db891bac29350cc694653bdae6a73d141ab9/src/DTS/eBaySDK/Trading/Types/ConditionValuesType.php#L26)

````php
@property \DTS\eBaySDK\Trading\Types\ConditionType[] $Condition
````

[] = array

**Comment by hpartidas** [comment]
@michabbb Indeed. I'm still kinda new at working with packages in packagist and composer (to my shame) despite having been coding for ever (at least it feels that way). So basically took a deep breath and dug into the code, reading source always gives me better understanding of things.

Props to @davidtsadler for great commented code as well!

**Comment by michabbb** [comment]
@hpartidas at this point (as usual) i have to recommend phpstorm, best php ide i know on this planet ;)
this tool helps you to get the correct types because of the phpdoc the gui can tell you, that something is not an array, but should be ;)

**Comment by hpartidas** [comment]
@michabbb phpstorm and/or anything from JetBrains is a must for any coder! I already have phpstorm but didn't get any sort of notification.

The only notification I do get is the "Unnecessary fully qualified name" warning. I often think that I don't have my phpstorm properly configured. =(
