### ISSUE TITLE
Can not Get Ebay Selling 

### ISSUE THREAD

**Issue by thebdcoder** [davidtsadler/ebay-sdk-trading#25]
When i try to call get my active selling list flowing the sample code here , 

https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/11-get-my-ebay-selling.php

i get an error like this ..

Error: Application name invalid. API application "202852" invalid.

**Comment by thebdcoder** [comment]
got it working buy setting the sandbox to true

**Comment by etsanov** [comment]
And how did you do that exactly? I changed the code in trading/02-get-category-hierarchy.php so that it says "sandbox" instead of "production" in both places where I found "production". I continue to get the error.
