### ISSUE TITLE
getFeedback CommentType - change unbound to false.

### ISSUE THREAD

**Issue by rossbulat** [davidtsadler/ebay-sdk-trading#26]
I was making a getFeedback request but the SDK was flagging an error when I assigned a CommentType, like so:

$request->CommentType    = Enums\CommentTypeCodeType::C_POSITIVE;

So I changed unbound to false in the GetFeedbackRequestType file and it worked.

**Comment by davidtsadler** [comment]
If you look at the [documentation for the CommentType field](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetFeedback.html#Request.CommentType) you should see that the *Occurrence* column indicates that the field is repeatable. This means that the API accepts multiple values for that field. In the SDK these fields will have `unbound` set to `true` and will allow you to specify multiple values by treating the field as an array. For example all the below are valid ways of setting the field.

```php
// Assign two values one at a time.
$request->CommentType[] = Enums\CommentTypeCodeType::C_POSITIVE;
$request->CommentType[] = Enums\CommentTypeCodeType::C_NEUTRAL;

// Assign an array of values.
$request->CommentType = [
	Enums\CommentTypeCodeType::C_POSITIVE, 
	Enums\CommentTypeCodeType::C_NEUTRAL
];
```
