### ISSUE TITLE
Deleting a Field with a ReviseFixedPriceItemRequestType

### ISSUE THREAD

**Issue by TheArceth** [davidtsadler/ebay-sdk-trading#27]
I am trying to delete a field within the ReviseFixedPriceItemRequestType call however no exception raised, however subtitle not removed.

 $request = new Types\ReviseFixedPriceItemRequestType();

        $request->RequesterCredentials = new Types\CustomSecurityHeaderType();
        $request->RequesterCredentials->eBayAuthToken = *****

        $item = new Types\ItemType();

            $request->DeletedField[] = "Item.SubTitle";

**Comment by davidtsadler** [comment]
At first glance it doesn't appear that you are doing anything wrong in the code. Keep in mind that there are [restrictions](http://pages.ebay.com/help/sell/revising_restrictions.html) on what and when you can revise an item. You may want to check the response for any messages returned from eBay as they may not be allowing the revision.

**Comment by TheArceth** [comment]
Thank you for your reply. This ended up being an issue with ebays caching system, that doesn't update in a timely manner.

It does in-fact remove the field after a period of about 10mins.

**Comment by davidtsadler** [comment]
Happy it's all sorted.
