### ISSUE TITLE
Missing merchandising api support

### ISSUE THREAD

**Issue by sjpatel** [davidtsadler/ebay-sdk-trading#28]
HI David,

This version currently seems not supporting merchandising api. Could you pls add support for the same.

**Comment by davidtsadler** [comment]
This SDK is no longer supported as it has been moved to a new [SDK](https://github.com/davidtsadler/ebay-sdk-php)  that supports several eBay services. This new SDK currently doesn't support [Merchandising](http://developer.ebay.com/DevZone/merchandising/docs/CallRef/index.html) but I can certainly look at adding it soon after version 1.0.0 of the SDK is released in the next month or so.
