### ISSUE TITLE
 Uncaught DTS\eBaySDK\Exceptions\InvalidPropertyTypeException: Invalid property type provided for ean.

### ISSUE THREAD

**Issue by ANDRIAMAHERY** [davidtsadler/ebay-sdk-trading#29]
I tried to create a inventory with an EAN property and I got this error:

**Fatal error**: Uncaught DTS\eBaySDK\Exceptions\InvalidPropertyTypeException: Invalid property type provided for ean. Expected DTS\eBaySDK\Types\RepeatableType but got string

Thanks,

**Comment by michabbb** [comment]
`<irony>` best way ever to report problems is: never show any code `</irony>`

**Comment by ANDRIAMAHERY** [comment]
OK thanks a lot,
You are right ;)

It is resolved
In fact it's half that was wrong, I just used 'my_ean_value' instead of [my_ean_value] :)

Thank you
