### ISSUE TITLE
Howto use CDATA ?

### ISSUE THREAD

**Issue by michabbb** [davidtsadler/ebay-sdk-trading#5]
hi david,

is there anything inside the SDK i have missed, where to tell the parser to use CDATA as default ? there are a lot of fields like title,subtitle,description where you can use a lot strange none xml conform chars... so it would be nice to use CDATA by default...
is this right now possible ? if not, any ideas ?

thanks a lot!
micha

**Comment by davidtsadler** [comment]
Version 1.0.0 of the SDK now [escapes characters](http://devbay.net/sdk/guides/guide/request-and-response-objects.html#html-converted-automatically) when constructing the XML.
